# Site settings
title:  过半人生存放区
description: "Sample Blog"
url:  "https://panssssy.github.io" # 博客地址
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Pass19" #你的昵称
  email: "812868525@qq.com" 
  url: "https://panssssy.github.io" # 博客地址
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 10 # 每页文章数
paginate_path: "/page:num/"

social:
  links: # 其他链接
    - https://@bybybyno@tzcafe.com
    - https://www.github.com/panssssy

webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never
  
# To use Gittalk comments  https://github.com/gitalk/gitalk#Usage
# jekyll synatx: https://jekyllrb.com/docs/liquid/
gittalk:
  # Note: A GitHub Application is needed for authorization, if you don't have one, going to https://github.com/settings/applications/new register a new one.
  # You must specify the website domain url in the Authorization callback URL field.
  clientID: d415c4ca05631298 # 改成你的 GitHub Application Client ID
  clientSecret: 88f6ed3cc8b878221ee9c8320d9aefb4122045dc  # 改成你的 GitHub Application Client Secret,
  repository: panssssy.github.io  # 改成你的 Storage gittalk's repository
  owner: panssssy # 改成你的 GitHub repo owner,
  admin: panssssy  # 改成你的 GitHub repo owner and collaborators, only these guys can initialize github issues eg. 'colynn,daattali'
